const BookFields = {
    BOOK_ID: 'id',
    TITLE: 'title',
    AUTHOR: 'author',
    SUB_TITLE: 'subTitle',
    IMAGE_URL: 'imageURL',
    ISBN: 'isbn',
    PUBLISHER: 'publisher',
    SERIES_TITLE: 'seriesTitle',
    EDITION: 'edition',
    LCCN: 'lccn',
    SUBJECTS: 'subjects',
    STATEMENT_OF_RESPONSIBILITY: 'statementOfResponsibility',
    NUMBER_OF_PAGES: 'numberOfPages',
    PUBLISHED_DATE: 'publishedDate',
    SUMMARY: 'summary',
    STUDY_PROGRAM: 'studyProgram',
    TITLE_POINTS: 'titlePoints',
    INTERNET_RESOURCE: 'internetResource',
    GENERAL_NOTE: 'generalNote',
    READING_LEVEL: 'readingLevel',
    RESOURCE_TYPE: 'resourceType',
    BARCODE: 'barcode',
    LOCATION: 'location',
    VENDOR: 'vendor',
    DATE: 'date',
    CALL_NUMBER: 'callNumber',
    CURRENCY: 'currency',
    FUND: 'fund',
    COST: 'cost'
};

export default BookFields;