export const PAGINATOR_NEXT = 'PAGINATOR_NEXT_';
export const PAGINATOR_PREVIOUS = 'PAGINATOR_PREVIOUS_';
export const PAGINATOR_FIRST = 'PAGINATOR_FIRST_';
export const PAGINATOR_LAST = 'PAGINATOR_LAST_';
export const PAGINATOR_REFRESH = 'PAGINATOR_REFRESH_';
export const PAGINATOR_GO_TO_PAGE = 'PAGINATOR_GO_TO_PAGE';
